#!/usr/bin/env python3

strings = []
names = {}

while True:
    try:
        strings.append(input())
    except EOFError:
        break

for string in strings:
    parts = string.split(":")
    if int(parts[2]) >= 1000:
        if parts[4] != '':
            name = parts[4].split()[0].capitalize()
            names[name] = names.get(name, 0) + 1

for name in names:
    print(f"{name}: {names[name]}")
